export interface CrisisResource {
  id: string;
  country: string;
  stateRegion?: string;
  city?: string;
  serviceName: string;
  crisisTypes: string[];
  phone?: string;
  phoneFormatted?: string;
  sms?: string;
  smsFormatted?: string;
  chatUrl?: string;
  website?: string;
  hours: string;
  languages: string[];
  audience: string[];
  is24_7: boolean;
  isFree: boolean;
  accessibilityOptions: string[];
  sourceName: string;
  sourceUrl: string;
  lastVerified: string;
  disclaimer: string;
}

export const VERIFIED_CRISIS_RESOURCES: CrisisResource[] = [
  // UNITED STATES - National
  {
    id: "us-988",
    country: "United States",
    serviceName: "988 Suicide & Crisis Lifeline",
    crisisTypes: ["suicide", "self-harm", "mental-health", "emotional-crisis", "substance-use"],
    phone: "988",
    phoneFormatted: "988",
    sms: "988",
    smsFormatted: "988",
    chatUrl: "https://988lifeline.org/chat",
    website: "https://988lifeline.org",
    hours: "24/7",
    languages: ["English", "Spanish", "Translation services for 250+ languages"],
    audience: ["all ages"],
    is24_7: true,
    isFree: true,
    accessibilityOptions: ["TTY: 711 then 988", "Video relay available", "Chat support"],
    sourceName: "SAMHSA / 988 Suicide & Crisis Lifeline",
    sourceUrl: "https://www.samhsa.gov/find-help/988",
    lastVerified: "2026-04-01",
    disclaimer: "Official U.S. government-designated crisis number. Calls routed to local crisis centers.",
  },
  {
    id: "us-911",
    country: "United States",
    serviceName: "Emergency Services",
    crisisTypes: ["immediate-danger", "life-threatening", "domestic-violence", "child-safety", "elder-abuse", "sexual-violence", "human-trafficking"],
    phone: "911",
    phoneFormatted: "911",
    hours: "24/7",
    languages: ["All languages (interpreters available)"],
    audience: ["all ages"],
    is24_7: true,
    isFree: true,
    accessibilityOptions: ["TTY available", "Text to 911 in many areas"],
    sourceName: "U.S. Government",
    sourceUrl: "https://www.usa.gov/emergency",
    lastVerified: "2026-04-01",
    disclaimer: "For immediate life-threatening emergencies only. Police, fire, ambulance.",
  },
  {
    id: "us-veterans",
    country: "United States",
    serviceName: "Veterans Crisis Line",
    crisisTypes: ["suicide", "self-harm", "mental-health", "veterans"],
    phone: "988",
    phoneFormatted: "988",
    sms: "838255",
    smsFormatted: "838255",
    chatUrl: "https://www.veteranscrisisline.net/get-help/chat",
    website: "https://www.veteranscrisisline.net",
    hours: "24/7",
    languages: ["English", "Spanish"],
    audience: ["veterans", "military", "family members"],
    is24_7: true,
    isFree: true,
    accessibilityOptions: ["TTY available"],
    sourceName: "U.S. Department of Veterans Affairs",
    sourceUrl: "https://www.veteranscrisisline.net",
    lastVerified: "2026-04-01",
    disclaimer: "For veterans, service members, and their families. Press 1 after dialing 988 or use direct number.",
  },
  {
    id: "us-crisis-text",
    country: "United States",
    serviceName: "Crisis Text Line",
    crisisTypes: ["suicide", "self-harm", "mental-health", "emotional-crisis", "anxiety", "depression"],
    sms: "741741",
    smsFormatted: "741741",
    chatUrl: "https://www.crisistextline.org",
    website: "https://www.crisistextline.org",
    hours: "24/7",
    languages: ["English", "Spanish"],
    audience: ["all ages"],
    is24_7: true,
    isFree: true,
    accessibilityOptions: ["Text only", "Chat via website"],
    sourceName: "Crisis Text Line",
    sourceUrl: "https://www.crisistextline.org",
    lastVerified: "2026-04-01",
    disclaimer: "Text HOME to 741741 from anywhere in the US, anytime.",
  },
  {
    id: "us-domestic-violence",
    country: "United States",
    serviceName: "National Domestic Violence Hotline",
    crisisTypes: ["domestic-violence", "abuse", "emotional-abuse"],
    phone: "800-799-7233",
    phoneFormatted: "8007997233",
    sms: "88788",
    smsFormatted: "88788",
    chatUrl: "https://www.thehotline.org",
    website: "https://www.thehotline.org",
    hours: "24/7",
    languages: ["English", "Spanish", "200+ languages through interpreter service"],
    audience: ["all ages", "all genders"],
    is24_7: true,
    isFree: true,
    accessibilityOptions: ["TTY: 800-787-3224", "Chat available"],
    sourceName: "National Domestic Violence Hotline",
    sourceUrl: "https://www.thehotline.org",
    lastVerified: "2026-04-01",
    disclaimer: "Confidential support for anyone experiencing domestic violence or seeking help for a loved one.",
  },
  {
    id: "us-samhsa",
    country: "United States",
    serviceName: "SAMHSA National Helpline",
    crisisTypes: ["substance-use", "mental-health", "emotional-crisis"],
    phone: "800-662-4357",
    phoneFormatted: "8006624357",
    website: "https://www.samhsa.gov/find-help/national-helpline",
    hours: "24/7 (English & Spanish)",
    languages: ["English", "Spanish"],
    audience: ["all ages"],
    is24_7: true,
    isFree: true,
    accessibilityOptions: ["TTY: 800-487-4889"],
    sourceName: "SAMHSA",
    sourceUrl: "https://www.samhsa.gov/find-help/national-helpline",
    lastVerified: "2026-04-01",
    disclaimer: "Free, confidential, 24/7 treatment referral and information service.",
  },
  {
    id: "us-childhelp",
    country: "United States",
    serviceName: "Childhelp National Child Abuse Hotline",
    crisisTypes: ["child-safety", "abuse", "child-abuse"],
    phone: "800-422-4453",
    phoneFormatted: "8004224453",
    sms: "800-422-4453",
    chatUrl: "https://www.childhelp.org/hotline",
    website: "https://www.childhelp.org",
    hours: "24/7",
    languages: ["English", "Spanish", "140+ languages"],
    audience: ["children", "teens", "parents", "mandated reporters"],
    is24_7: true,
    isFree: true,
    accessibilityOptions: ["Chat available"],
    sourceName: "Childhelp",
    sourceUrl: "https://www.childhelp.org",
    lastVerified: "2026-04-01",
    disclaimer: "Professional crisis counselors available 24/7 for child abuse concerns.",
  },
  {
    id: "us-rainn",
    country: "United States",
    serviceName: "RAINN National Sexual Assault Hotline",
    crisisTypes: ["sexual-violence", "sexual-assault", "abuse"],
    phone: "800-656-4673",
    phoneFormatted: "8006564673",
    chatUrl: "https://www.rainn.org",
    website: "https://www.rainn.org",
    hours: "24/7",
    languages: ["English", "Spanish"],
    audience: ["all ages", "all genders"],
    is24_7: true,
    isFree: true,
    accessibilityOptions: ["Chat available"],
    sourceName: "RAINN (Rape, Abuse & Incest National Network)",
    sourceUrl: "https://www.rainn.org",
    lastVerified: "2026-04-01",
    disclaimer: "Confidential support for survivors of sexual violence.",
  },
  {
    id: "us-trevor",
    country: "United States",
    serviceName: "The Trevor Project",
    crisisTypes: ["suicide", "self-harm", "mental-health", "lgbtq", "identity-crisis"],
    phone: "866-488-7386",
    phoneFormatted: "8664887386",
    sms: "678-678",
    smsFormatted: "678678",
    chatUrl: "https://www.thetrevorproject.org/get-help",
    website: "https://www.thetrevorproject.org",
    hours: "24/7",
    languages: ["English", "Spanish"],
    audience: ["LGBTQ+ youth", "young adults", "questioning"],
    is24_7: true,
    isFree: true,
    accessibilityOptions: ["Chat", "Text"],
    sourceName: "The Trevor Project",
    sourceUrl: "https://www.thetrevorproject.org",
    lastVerified: "2026-04-01",
    disclaimer: "Crisis intervention and suicide prevention for LGBTQ+ young people under 25.",
  },
  {
    id: "us-trans-lifeline",
    country: "United States",
    serviceName: "Trans Lifeline",
    crisisTypes: ["suicide", "self-harm", "mental-health", "lgbtq", "transgender", "identity-crisis"],
    phone: "877-565-8860",
    phoneFormatted: "8775658860",
    website: "https://translifeline.org",
    hours: "Daily (varies by state, check website)",
    languages: ["English", "Spanish"],
    audience: ["transgender", "non-binary", "gender diverse"],
    is24_7: false,
    isFree: true,
    accessibilityOptions: ["Hotline only"],
    sourceName: "Trans Lifeline",
    sourceUrl: "https://translifeline.org",
    lastVerified: "2026-04-01",
    disclaimer: "Peer support hotline run by and for trans people.",
  },

  // CANADA
  {
    id: "ca-911",
    country: "Canada",
    serviceName: "Emergency Services",
    crisisTypes: ["immediate-danger", "life-threatening", "domestic-violence", "child-safety"],
    phone: "911",
    phoneFormatted: "911",
    hours: "24/7",
    languages: ["English", "French"],
    audience: ["all ages"],
    is24_7: true,
    isFree: true,
    accessibilityOptions: ["TTY available"],
    sourceName: "Government of Canada",
    sourceUrl: "https://www.publicsafety.gc.ca",
    lastVerified: "2026-04-01",
    disclaimer: "For immediate life-threatening emergencies.",
  },
  {
    id: "ca-988",
    country: "Canada",
    serviceName: "988 Suicide Crisis Helpline",
    crisisTypes: ["suicide", "self-harm", "mental-health", "emotional-crisis"],
    phone: "988",
    phoneFormatted: "988",
    hours: "24/7",
    languages: ["English", "French"],
    audience: ["all ages"],
    is24_7: true,
    isFree: true,
    accessibilityOptions: ["Text available in some regions"],
    sourceName: "Government of Canada / Centre for Addiction and Mental Health",
    sourceUrl: "https://988.ca",
    lastVerified: "2026-04-01",
    disclaimer: "Canada's national suicide prevention helpline. Free, confidential, 24/7.",
  },
  {
    id: "ca-kids-help",
    country: "Canada",
    serviceName: "Kids Help Phone",
    crisisTypes: ["suicide", "self-harm", "mental-health", "emotional-crisis", "abuse"],
    phone: "800-668-6868",
    phoneFormatted: "8006686868",
    sms: "686868",
    smsFormatted: "686868",
    chatUrl: "https://kidshelpphone.ca",
    website: "https://kidshelpphone.ca",
    hours: "24/7",
    languages: ["English", "French"],
    audience: ["youth", "children", "teens", "young adults"],
    is24_7: true,
    isFree: true,
    accessibilityOptions: ["Chat", "Text", "Phone"],
    sourceName: "Kids Help Phone",
    sourceUrl: "https://kidshelpphone.ca",
    lastVerified: "2026-04-01",
    disclaimer: "Canada's only 24/7 support service for young people. Free, confidential, anonymous.",
  },

  // UNITED KINGDOM
  {
    id: "uk-999",
    country: "United Kingdom",
    serviceName: "Emergency Services",
    crisisTypes: ["immediate-danger", "life-threatening", "domestic-violence", "child-safety"],
    phone: "999",
    phoneFormatted: "999",
    hours: "24/7",
    languages: ["English", "Welsh", "Interpreters available"],
    audience: ["all ages"],
    is24_7: true,
    isFree: true,
    accessibilityOptions: ["Text relay: 18000", "BSL interpreter via app"],
    sourceName: "UK Government",
    sourceUrl: "https://www.gov.uk/call-emergency-services",
    lastVerified: "2026-04-01",
    disclaimer: "For immediate life-threatening emergencies. Police, fire, ambulance.",
  },
  {
    id: "uk-111",
    country: "United Kingdom",
    serviceName: "NHS 111 (Mental Health Option)",
    crisisTypes: ["mental-health", "emotional-crisis", "health-concern"],
    phone: "111",
    phoneFormatted: "111",
    website: "https://111.nhs.uk",
    hours: "24/7",
    languages: ["English", "Interpretation available"],
    audience: ["all ages"],
    is24_7: true,
    isFree: true,
    accessibilityOptions: ["Text relay", "BSL"],
    sourceName: "NHS",
    sourceUrl: "https://www.nhs.uk/nhs-services/urgent-and-emergency-care/nhs-111/",
    lastVerified: "2026-04-01",
    disclaimer: "NHS non-emergency medical helpline. Select mental health option for crisis support.",
  },
  {
    id: "uk-samaritans",
    country: "United Kingdom",
    serviceName: "Samaritans",
    crisisTypes: ["suicide", "self-harm", "mental-health", "emotional-crisis", "loneliness"],
    phone: "116 123",
    phoneFormatted: "116123",
    website: "https://www.samaritans.org",
    hours: "24/7",
    languages: ["English", "Welsh"],
    audience: ["all ages"],
    is24_7: true,
    isFree: true,
    accessibilityOptions: ["Email support", "BSL video relay", "Text relay"],
    sourceName: "Samaritans",
    sourceUrl: "https://www.samaritans.org",
    lastVerified: "2026-04-01",
    disclaimer: "Free, confidential emotional support 24/7. Call 116 123 (UK and ROI).",
  },
  {
    id: "uk-shout",
    country: "United Kingdom",
    serviceName: "SHOUT Crisis Text Line",
    crisisTypes: ["suicide", "self-harm", "mental-health", "emotional-crisis", "anxiety", "depression"],
    sms: "85258",
    smsFormatted: "85258",
    website: "https://giveusashout.org",
    hours: "24/7",
    languages: ["English"],
    audience: ["all ages"],
    is24_7: true,
    isFree: true,
    accessibilityOptions: ["Text only"],
    sourceName: "SHOUT / Crisis Text Line UK",
    sourceUrl: "https://giveusashout.org",
    lastVerified: "2026-04-01",
    disclaimer: "Free, confidential 24/7 text support. Text SHOUT to 85258.",
  },
  {
    id: "uk-childline",
    country: "United Kingdom",
    serviceName: "Childline",
    crisisTypes: ["child-safety", "abuse", "mental-health", "suicide", "self-harm", "bullying"],
    phone: "0800 1111",
    phoneFormatted: "08001111",
    chatUrl: "https://www.childline.org.uk",
    website: "https://www.childline.org.uk",
    hours: "24/7 (phone, chat varies by time)",
    languages: ["English", "Interpretation available"],
    audience: ["children", "teens", "young people under 19"],
    is24_7: true,
    isFree: true,
    accessibilityOptions: ["Chat", "Email", "BSL"],
    sourceName: "Childline / NSPCC",
    sourceUrl: "https://www.childline.org.uk",
    lastVerified: "2026-04-01",
    disclaimer: "Free, private and confidential service for children and young people in the UK.",
  },
  {
    id: "uk-refuge",
    country: "United Kingdom",
    serviceName: "National Domestic Abuse Helpline",
    crisisTypes: ["domestic-violence", "abuse", "emotional-abuse"],
    phone: "0808 2000 247",
    phoneFormatted: "08082000247",
    website: "https://www.nationaldahelpline.org.uk",
    hours: "24/7",
    languages: ["English", "Interpretation available"],
    audience: ["all ages", "all genders"],
    is24_7: true,
    isFree: true,
    accessibilityOptions: ["BSL", "Text relay"],
    sourceName: "Refuge / National Domestic Abuse Helpline",
    sourceUrl: "https://www.nationaldahelpline.org.uk",
    lastVerified: "2026-04-01",
    disclaimer: "Free, confidential 24/7 domestic abuse helpline.",
  },

  // NIGERIA
  {
    id: "ng-112",
    country: "Nigeria",
    serviceName: "Emergency Services",
    crisisTypes: ["immediate-danger", "life-threatening", "domestic-violence", "child-safety"],
    phone: "112",
    phoneFormatted: "112",
    hours: "24/7",
    languages: ["English", "Local languages available"],
    audience: ["all ages"],
    is24_7: true,
    isFree: true,
    accessibilityOptions: ["Call only"],
    sourceName: "Nigeria Emergency Management Agency (NEMA)",
    sourceUrl: "https://nema.gov.ng",
    lastVerified: "2026-04-01",
    disclaimer: "National emergency number. Police, fire, ambulance, and road safety.",
  },
  {
    id: "ng-mani",
    country: "Nigeria",
    serviceName: "Mentally Aware Nigeria Initiative (MANI)",
    crisisTypes: ["suicide", "self-harm", "mental-health", "emotional-crisis", "depression", "anxiety"],
    phone: "0809 210 6493",
    phoneFormatted: "+2348092106493",
    website: "https://www.mentallyaware.org",
    hours: "Daily, 8am-10pm (WAT)",
    languages: ["English", "Pidgin"],
    audience: ["all ages", "youth", "adults"],
    is24_7: false,
    isFree: true,
    accessibilityOptions: ["Phone support", "Social media outreach"],
    sourceName: "Mentally Aware Nigeria Initiative",
    sourceUrl: "https://www.mentallyaware.org",
    lastVerified: "2026-04-01",
    disclaimer: "Nigeria's leading mental health advocacy organization. Crisis intervention and referral.",
  },

  // GHANA
  {
    id: "gh-112",
    country: "Ghana",
    serviceName: "Emergency Services",
    crisisTypes: ["immediate-danger", "life-threatening"],
    phone: "112",
    phoneFormatted: "112",
    hours: "24/7",
    languages: ["English", "Local languages"],
    audience: ["all ages"],
    is24_7: true,
    isFree: true,
    accessibilityOptions: ["Call only"],
    sourceName: "Ghana National Fire Service / Police",
    sourceUrl: "https://www.police.gov.gh",
    lastVerified: "2026-04-01",
    disclaimer: "National emergency number for police, fire, and ambulance.",
  },

  // KENYA
  {
    id: "ke-999",
    country: "Kenya",
    serviceName: "Emergency Services",
    crisisTypes: ["immediate-danger", "life-threatening"],
    phone: "999",
    phoneFormatted: "999",
    hours: "24/7",
    languages: ["English", "Swahili"],
    audience: ["all ages"],
    is24_7: true,
    isFree: true,
    accessibilityOptions: ["Call only"],
    sourceName: "Kenya Police Service",
    sourceUrl: "https://www.nationalpolice.go.ke",
    lastVerified: "2026-04-01",
    disclaimer: "National emergency number for police, fire, and ambulance.",
  },
  {
    id: "ke-befrienders",
    country: "Kenya",
    serviceName: "Befrienders Kenya / Niskize",
    crisisTypes: ["suicide", "self-harm", "mental-health", "emotional-crisis", "depression"],
    phone: "+254 722 178 177",
    phoneFormatted: "+254722178177",
    website: "https://www.befrienderskenya.org",
    hours: "Daily, 2pm-10pm (EAT)",
    languages: ["English", "Swahili"],
    audience: ["all ages"],
    is24_7: false,
    isFree: true,
    accessibilityOptions: ["Phone support"],
    sourceName: "Befrienders Kenya",
    sourceUrl: "https://www.befrienderskenya.org",
    lastVerified: "2026-04-01",
    disclaimer: "Emotional support for those experiencing distress or suicidal feelings.",
  },

  // SOUTH AFRICA
  {
    id: "za-10111",
    country: "South Africa",
    serviceName: "Emergency Services",
    crisisTypes: ["immediate-danger", "life-threatening", "domestic-violence"],
    phone: "10111",
    phoneFormatted: "10111",
    hours: "24/7",
    languages: ["English", "Afrikaans", "Zulu", "Xhosa", "Other local languages"],
    audience: ["all ages"],
    is24_7: true,
    isFree: true,
    accessibilityOptions: ["Call only"],
    sourceName: "South African Police Service",
    sourceUrl: "https://www.saps.gov.za",
    lastVerified: "2026-04-01",
    disclaimer: "National police emergency number. For ambulance call 10177.",
  },
  {
    id: "za-sadag",
    country: "South Africa",
    serviceName: "SADAG Suicide Crisis Helpline",
    crisisTypes: ["suicide", "self-harm", "mental-health", "emotional-crisis", "depression", "anxiety"],
    phone: "0800 567 567",
    phoneFormatted: "+27800567567",
    website: "https://www.sadag.org",
    hours: "24/7",
    languages: ["English", "Afrikaans", "Zulu", "Xhosa"],
    audience: ["all ages"],
    is24_7: true,
    isFree: true,
    accessibilityOptions: ["Phone support", "SMS support available"],
    sourceName: "South African Depression and Anxiety Group (SADAG)",
    sourceUrl: "https://www.sadag.org",
    lastVerified: "2026-04-01",
    disclaimer: "South Africa's largest mental health support organization. Free crisis line.",
  },

  // INDIA
  {
    id: "in-112",
    country: "India",
    serviceName: "Emergency Services",
    crisisTypes: ["immediate-danger", "life-threatening"],
    phone: "112",
    phoneFormatted: "112",
    hours: "24/7",
    languages: ["English", "Hindi", "Regional languages"],
    audience: ["all ages"],
    is24_7: true,
    isFree: true,
    accessibilityOptions: ["Call only"],
    sourceName: "Government of India",
    sourceUrl: "https://www.mha.gov.in",
    lastVerified: "2026-04-01",
    disclaimer: "Unified emergency number for police, fire, and ambulance.",
  },
  {
    id: "in-icall",
    country: "India",
    serviceName: "iCall Mental Health Helpline",
    crisisTypes: ["suicide", "self-harm", "mental-health", "emotional-crisis", "depression", "anxiety"],
    phone: "+91 9152 987 821",
    phoneFormatted: "+919152987821",
    website: "https://icallhelpline.org",
    hours: "Monday-Saturday, 10am-8pm (IST)",
    languages: ["English", "Hindi", "Marathi", "Bengali", "Tamil", "Telugu", "Kannada", "Gujarati"],
    audience: ["all ages"],
    is24_7: false,
    isFree: true,
    accessibilityOptions: ["Phone", "Email"],
    sourceName: "iCall / Tata Institute of Social Sciences",
    sourceUrl: "https://icallhelpline.org",
    lastVerified: "2026-04-01",
    disclaimer: "Professional telephone and email counselling.",
  },

  // AUSTRALIA
  {
    id: "au-000",
    country: "Australia",
    serviceName: "Emergency Services",
    crisisTypes: ["immediate-danger", "life-threatening", "domestic-violence"],
    phone: "000",
    phoneFormatted: "000",
    hours: "24/7",
    languages: ["English", "Interpretation service available"],
    audience: ["all ages"],
    is24_7: true,
    isFree: true,
    accessibilityOptions: ["TTY: 106", "SMS relay"],
    sourceName: "Australian Government",
    sourceUrl: "https://www.triplezero.gov.au",
    lastVerified: "2026-04-01",
    disclaimer: "National emergency number for police, fire, and ambulance.",
  },
  {
    id: "au-lifeline",
    country: "Australia",
    serviceName: "Lifeline Australia",
    crisisTypes: ["suicide", "self-harm", "mental-health", "emotional-crisis", "depression", "anxiety"],
    phone: "13 11 14",
    phoneFormatted: "131114",
    sms: "0477 13 11 14",
    smsFormatted: "0477131114",
    chatUrl: "https://www.lifeline.org.au/get-help/online-crisis-support",
    website: "https://www.lifeline.org.au",
    hours: "24/7",
    languages: ["English", "Interpretation service available"],
    audience: ["all ages"],
    is24_7: true,
    isFree: true,
    accessibilityOptions: ["Chat", "Text", "Phone"],
    sourceName: "Lifeline Australia",
    sourceUrl: "https://www.lifeline.org.au",
    lastVerified: "2026-04-01",
    disclaimer: "Australia's leading crisis support service. Free, confidential, 24/7.",
  },
  {
    id: "au-kidsline",
    country: "Australia",
    serviceName: "Kids Helpline",
    crisisTypes: ["suicide", "self-harm", "mental-health", "emotional-crisis", "abuse", "bullying"],
    phone: "1800 55 1800",
    phoneFormatted: "1800551800",
    chatUrl: "https://kidshelpline.com.au",
    website: "https://kidshelpline.com.au",
    hours: "24/7",
    languages: ["English"],
    audience: ["children", "teens", "young people 5–25"],
    is24_7: true,
    isFree: true,
    accessibilityOptions: ["Chat", "Phone"],
    sourceName: "Kids Helpline / yourtown",
    sourceUrl: "https://kidshelpline.com.au",
    lastVerified: "2026-04-01",
    disclaimer: "Australia's only free, private and confidential 24/7 phone and online counselling service for young people.",
  },

  // NEW ZEALAND
  {
    id: "nz-111",
    country: "New Zealand",
    serviceName: "Emergency Services",
    crisisTypes: ["immediate-danger", "life-threatening"],
    phone: "111",
    phoneFormatted: "111",
    hours: "24/7",
    languages: ["English", "Maori", "Interpretation service available"],
    audience: ["all ages"],
    is24_7: true,
    isFree: true,
    accessibilityOptions: ["TTY: 0800 161 610", "Text relay"],
    sourceName: "New Zealand Police",
    sourceUrl: "https://www.police.govt.nz",
    lastVerified: "2026-04-01",
    disclaimer: "National emergency number for police, fire, and ambulance.",
  },
  {
    id: "nz-1737",
    country: "New Zealand",
    serviceName: "1737 Need to Talk?",
    crisisTypes: ["suicide", "self-harm", "mental-health", "emotional-crisis", "depression", "anxiety", "loneliness"],
    phone: "1737",
    phoneFormatted: "1737",
    sms: "1737",
    smsFormatted: "1737",
    website: "https://1737.org.nz",
    hours: "24/7",
    languages: ["English", "Maori", "Interpretation available"],
    audience: ["all ages"],
    is24_7: true,
    isFree: true,
    accessibilityOptions: ["Phone", "Text"],
    sourceName: "New Zealand Ministry of Health",
    sourceUrl: "https://1737.org.nz",
    lastVerified: "2026-04-01",
    disclaimer: "Free, confidential 24/7 support from trained counsellors. Call or text 1737.",
  },

  // GERMANY
  {
    id: "de-112",
    country: "Germany",
    serviceName: "Emergency Services",
    crisisTypes: ["immediate-danger", "life-threatening"],
    phone: "112",
    phoneFormatted: "112",
    hours: "24/7",
    languages: ["German", "English"],
    audience: ["all ages"],
    is24_7: true,
    isFree: true,
    accessibilityOptions: ["Call only"],
    sourceName: "German Government",
    sourceUrl: "https://www.bundesregierung.de",
    lastVerified: "2026-04-01",
    disclaimer: "EU-wide emergency number for fire and ambulance. For police call 110.",
  },
  {
    id: "de-telefonseelsorge",
    country: "Germany",
    serviceName: "Telefonseelsorge (Crisis Hotline)",
    crisisTypes: ["suicide", "self-harm", "mental-health", "emotional-crisis", "depression", "loneliness"],
    phone: "0800 111 0 111",
    phoneFormatted: "08001110111",
    website: "https://www.telefonseelsorge.de",
    hours: "24/7",
    languages: ["German"],
    audience: ["all ages"],
    is24_7: true,
    isFree: true,
    accessibilityOptions: ["Phone", "Chat available"],
    sourceName: "Telefonseelsorge Deutschland",
    sourceUrl: "https://www.telefonseelsorge.de",
    lastVerified: "2026-04-01",
    disclaimer: "Free, confidential 24/7 crisis counselling. Also available at 0800 111 0 222.",
  },
  {
    id: "de-nummergegenkummer",
    country: "Germany",
    serviceName: "Nummer gegen Kummer (Children & Youth)",
    crisisTypes: ["suicide", "self-harm", "mental-health", "abuse", "bullying", "emotional-crisis"],
    phone: "116 111",
    phoneFormatted: "116111",
    website: "https://www.nummergegenkummer.de",
    hours: "Monday-Saturday, 2pm-8pm",
    languages: ["German"],
    audience: ["children", "teens", "young people"],
    is24_7: false,
    isFree: true,
    accessibilityOptions: ["Phone", "Chat"],
    sourceName: "Nummer gegen Kummer e.V.",
    sourceUrl: "https://www.nummergegenkummer.de",
    lastVerified: "2026-04-01",
    disclaimer: "Free, anonymous counselling for children and young people.",
  },

  // FRANCE
  {
    id: "fr-112",
    country: "France",
    serviceName: "Emergency Services",
    crisisTypes: ["immediate-danger", "life-threatening"],
    phone: "112",
    phoneFormatted: "112",
    hours: "24/7",
    languages: ["French", "English"],
    audience: ["all ages"],
    is24_7: true,
    isFree: true,
    accessibilityOptions: ["Call only"],
    sourceName: "French Government",
    sourceUrl: "https://www.service-public.fr",
    lastVerified: "2026-04-01",
    disclaimer: "EU-wide emergency number. Police: 17, Fire: 18, Ambulance: 15.",
  },
  {
    id: "fr-sos-amitie",
    country: "France",
    serviceName: "SOS Amitié",
    crisisTypes: ["suicide", "self-harm", "mental-health", "emotional-crisis", "loneliness", "depression"],
    phone: "09 72 39 40 50",
    phoneFormatted: "0972394050",
    website: "https://www.sos-amitie.org",
    hours: "24/7",
    languages: ["French"],
    audience: ["all ages"],
    is24_7: true,
    isFree: true,
    accessibilityOptions: ["Phone", "Chat available"],
    sourceName: "SOS Amitié",
    sourceUrl: "https://www.sos-amitie.org",
    lastVerified: "2026-04-01",
    disclaimer: "Free, confidential emotional support 24/7.",
  },

  // SPAIN
  {
    id: "es-112",
    country: "Spain",
    serviceName: "Emergency Services",
    crisisTypes: ["immediate-danger", "life-threatening"],
    phone: "112",
    phoneFormatted: "112",
    hours: "24/7",
    languages: ["Spanish", "Catalan", "Basque", "Galician", "English"],
    audience: ["all ages"],
    is24_7: true,
    isFree: true,
    accessibilityOptions: ["Call only"],
    sourceName: "Spanish Government",
    sourceUrl: "https://www.proteccioncivil.es",
    lastVerified: "2026-04-01",
    disclaimer: "EU-wide emergency number.",
  },
  {
    id: "es-telefono-esperanza",
    country: "Spain",
    serviceName: "Teléfono de la Esperanza",
    crisisTypes: ["suicide", "self-harm", "mental-health", "emotional-crisis", "loneliness", "depression", "anxiety"],
    phone: "717 003 717",
    phoneFormatted: "717003717",
    website: "https://www.telefonodelaesperanza.org",
    hours: "24/7",
    languages: ["Spanish", "Catalan"],
    audience: ["all ages"],
    is24_7: true,
    isFree: true,
    accessibilityOptions: ["Phone", "Chat", "Email"],
    sourceName: "Teléfono de la Esperanza",
    sourceUrl: "https://www.telefonodelaesperanza.org",
    lastVerified: "2026-04-01",
    disclaimer: "Free, confidential crisis support 24/7.",
  },

  // BRAZIL
  {
    id: "br-188",
    country: "Brazil",
    serviceName: "Centro de Valorização da Vida (CVV)",
    crisisTypes: ["suicide", "self-harm", "mental-health", "emotional-crisis", "loneliness", "depression"],
    phone: "188",
    phoneFormatted: "188",
    chatUrl: "https://www.cvv.org.br",
    website: "https://www.cvv.org.br",
    hours: "24/7",
    languages: ["Portuguese"],
    audience: ["all ages"],
    is24_7: true,
    isFree: true,
    accessibilityOptions: ["Phone", "Chat", "Email"],
    sourceName: "Centro de Valorização da Vida",
    sourceUrl: "https://www.cvv.org.br",
    lastVerified: "2026-04-01",
    disclaimer: "Brazil's national suicide prevention and emotional support hotline. Free, confidential, 24/7.",
  },

  // MEXICO
  {
    id: "mx-911",
    country: "Mexico",
    serviceName: "Emergency Services",
    crisisTypes: ["immediate-danger", "life-threatening"],
    phone: "911",
    phoneFormatted: "911",
    hours: "24/7",
    languages: ["Spanish", "English"],
    audience: ["all ages"],
    is24_7: true,
    isFree: true,
    accessibilityOptions: ["Call only"],
    sourceName: "Mexican Government",
    sourceUrl: "https://www.gob.mx",
    lastVerified: "2026-04-01",
    disclaimer: "National emergency number for police, fire, and ambulance.",
  },
  {
    id: "mx-saptel",
    country: "Mexico",
    serviceName: "SAPTEL Crisis Line",
    crisisTypes: ["suicide", "self-harm", "mental-health", "emotional-crisis", "depression", "anxiety"],
    phone: "800 911 2000",
    phoneFormatted: "8009112000",
    website: "https://www.gob.mx/salud",
    hours: "24/7",
    languages: ["Spanish"],
    audience: ["all ages"],
    is24_7: true,
    isFree: true,
    accessibilityOptions: ["Phone only"],
    sourceName: "Secretaría de Salud (Mexico Ministry of Health)",
    sourceUrl: "https://www.gob.mx/salud",
    lastVerified: "2026-04-01",
    disclaimer: "Free 24/7 psychological support hotline.",
  },

  // JAPAN
  {
    id: "jp-110",
    country: "Japan",
    serviceName: "Emergency Services",
    crisisTypes: ["immediate-danger", "life-threatening"],
    phone: "110",
    phoneFormatted: "110",
    hours: "24/7",
    languages: ["Japanese", "English interpretation available"],
    audience: ["all ages"],
    is24_7: true,
    isFree: true,
    accessibilityOptions: ["Call only"],
    sourceName: "National Police Agency of Japan",
    sourceUrl: "https://www.npa.go.jp",
    lastVerified: "2026-04-01",
    disclaimer: "Police emergency. For ambulance/fire call 119.",
  },
  {
    id: "jp-inochi",
    country: "Japan",
    serviceName: "Inochi no Denwa (Lifeline)",
    crisisTypes: ["suicide", "self-harm", "mental-health", "emotional-crisis", "loneliness"],
    phone: "0120 783 556",
    phoneFormatted: "0120783556",
    website: "https://www.inochinodenwa.jp",
    hours: "Daily, 10am-10pm (JST)",
    languages: ["Japanese"],
    audience: ["all ages"],
    is24_7: false,
    isFree: true,
    accessibilityOptions: ["Phone only"],
    sourceName: "Inochi no Denwa",
    sourceUrl: "https://www.inochinodenwa.jp",
    lastVerified: "2026-04-01",
    disclaimer: "Japan's oldest suicide prevention hotline. Free and confidential.",
  },

  // SOUTH KOREA
  {
    id: "kr-112",
    country: "South Korea",
    serviceName: "Emergency Services",
    crisisTypes: ["immediate-danger", "life-threatening"],
    phone: "112",
    phoneFormatted: "112",
    hours: "24/7",
    languages: ["Korean", "English interpretation available"],
    audience: ["all ages"],
    is24_7: true,
    isFree: true,
    accessibilityOptions: ["Call only"],
    sourceName: "Korean National Police Agency",
    sourceUrl: "https://www.police.go.kr",
    lastVerified: "2026-04-01",
    disclaimer: "Police emergency. For ambulance/fire call 119.",
  },
  {
    id: "kr-1393",
    country: "South Korea",
    serviceName: "Korea Suicide Prevention Hotline",
    crisisTypes: ["suicide", "self-harm", "mental-health", "emotional-crisis", "depression"],
    phone: "1393",
    phoneFormatted: "1393",
    website: "https://www.kfsp.or.kr",
    hours: "24/7",
    languages: ["Korean"],
    audience: ["all ages"],
    is24_7: true,
    isFree: true,
    accessibilityOptions: ["Phone only"],
    sourceName: "Korea Foundation for Suicide Prevention",
    sourceUrl: "https://www.kfsp.or.kr",
    lastVerified: "2026-04-01",
    disclaimer: "National suicide prevention hotline. Free and confidential.",
  },

  // PHILIPPINES
  {
    id: "ph-911",
    country: "Philippines",
    serviceName: "Emergency Services",
    crisisTypes: ["immediate-danger", "life-threatening"],
    phone: "911",
    phoneFormatted: "911",
    hours: "24/7",
    languages: ["Filipino", "English"],
    audience: ["all ages"],
    is24_7: true,
    isFree: true,
    accessibilityOptions: ["Call only"],
    sourceName: "Philippine National Police",
    sourceUrl: "https://www.pnp.gov.ph",
    lastVerified: "2026-04-01",
    disclaimer: "National emergency number.",
  },
  {
    id: "ph-hopeline",
    country: "Philippines",
    serviceName: "Hopeline PH",
    crisisTypes: ["suicide", "self-harm", "mental-health", "emotional-crisis", "depression", "anxiety"],
    phone: "+63 2 8804 4673",
    phoneFormatted: "+63288044673",
    website: "https://hopeline.com.ph",
    hours: "24/7",
    languages: ["Filipino", "English"],
    audience: ["all ages"],
    is24_7: true,
    isFree: true,
    accessibilityOptions: ["Phone only"],
    sourceName: "Natasha Goulbourn Foundation",
    sourceUrl: "https://hopeline.com.ph",
    lastVerified: "2026-04-01",
    disclaimer: "Free, confidential crisis support hotline in the Philippines.",
  },

  // INTERNATIONAL / GLOBAL
  {
    id: "global-findahelpline",
    country: "Global",
    serviceName: "Find a Helpline",
    crisisTypes: ["suicide", "self-harm", "mental-health", "emotional-crisis", "all-crisis"],
    chatUrl: "https://findahelpline.com",
    website: "https://findahelpline.com",
    hours: "Varies by country",
    languages: ["Multiple languages", "Search by language"],
    audience: ["all ages", "all countries"],
    is24_7: false,
    isFree: true,
    accessibilityOptions: ["Search by country", "Search by language", "Search by crisis type"],
    sourceName: "Throughline / Open Sums",
    sourceUrl: "https://findahelpline.com",
    lastVerified: "2026-04-01",
    disclaimer: "Global directory of verified crisis helplines. Covers 130+ countries.",
  },
  {
    id: "global-befrienders",
    country: "Global",
    serviceName: "Befrienders Worldwide",
    crisisTypes: ["suicide", "self-harm", "mental-health", "emotional-crisis", "loneliness"],
    website: "https://www.befrienders.org",
    hours: "Varies by center",
    languages: ["Multiple languages"],
    audience: ["all ages"],
    is24_7: false,
    isFree: true,
    accessibilityOptions: ["Search by country"],
    sourceName: "Befrienders Worldwide",
    sourceUrl: "https://www.befrienders.org",
    lastVerified: "2026-04-01",
    disclaimer: "International network of emotional support centers in 30+ countries.",
  },
  {
    id: "global-iasp",
    country: "Global",
    serviceName: "IASP Crisis Centres",
    crisisTypes: ["suicide", "self-harm"],
    website: "https://www.iasp.info/resources/Crisis_Centres",
    hours: "Varies by center",
    languages: ["Multiple languages"],
    audience: ["all ages"],
    is24_7: false,
    isFree: true,
    accessibilityOptions: ["Search by country"],
    sourceName: "International Association for Suicide Prevention",
    sourceUrl: "https://www.iasp.info/resources/Crisis_Centres",
    lastVerified: "2026-04-01",
    disclaimer: "Directory of crisis centers worldwide maintained by IASP.",
  },
];

export const COUNTRIES = [
  { name: "United States", code: "US" },
  { name: "Canada", code: "CA" },
  { name: "United Kingdom", code: "GB" },
  { name: "Nigeria", code: "NG" },
  { name: "Ghana", code: "GH" },
  { name: "Kenya", code: "KE" },
  { name: "South Africa", code: "ZA" },
  { name: "India", code: "IN" },
  { name: "Pakistan", code: "PK" },
  { name: "Bangladesh", code: "BD" },
  { name: "United Arab Emirates", code: "AE" },
  { name: "Saudi Arabia", code: "SA" },
  { name: "Qatar", code: "QA" },
  { name: "Turkey", code: "TR" },
  { name: "Australia", code: "AU" },
  { name: "New Zealand", code: "NZ" },
  { name: "Germany", code: "DE" },
  { name: "France", code: "FR" },
  { name: "Italy", code: "IT" },
  { name: "Spain", code: "ES" },
  { name: "Ireland", code: "IE" },
  { name: "Netherlands", code: "NL" },
  { name: "Belgium", code: "BE" },
  { name: "Sweden", code: "SE" },
  { name: "Norway", code: "NO" },
  { name: "Denmark", code: "DK" },
  { name: "Finland", code: "FI" },
  { name: "Brazil", code: "BR" },
  { name: "Mexico", code: "MX" },
  { name: "Jamaica", code: "JM" },
  { name: "Trinidad and Tobago", code: "TT" },
  { name: "Philippines", code: "PH" },
  { name: "Malaysia", code: "MY" },
  { name: "Singapore", code: "SG" },
  { name: "Indonesia", code: "ID" },
  { name: "Japan", code: "JP" },
  { name: "South Korea", code: "KR" },
  { name: "China", code: "CN" },
];

export const US_STATES = [
  "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "Florida", "Georgia",
  "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland",
  "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey",
  "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina",
  "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming",
];

export const CRISIS_TYPES = [
  "suicide",
  "self-harm",
  "immediate-danger",
  "domestic-violence",
  "sexual-violence",
  "child-safety",
  "elder-abuse",
  "human-trafficking",
  "mental-health",
  "emotional-crisis",
  "substance-use",
  "homelessness",
  "caregiver-crisis",
  "disability-emergency",
  "lgbtq",
  "veterans",
  "abuse",
  "bullying",
];

export function getResourcesByCountry(country: string): CrisisResource[] {
  return VERIFIED_CRISIS_RESOURCES.filter(
    (r) => r.country === country || r.country === "Global"
  );
}

export function getResourcesByCrisisType(type: string): CrisisResource[] {
  return VERIFIED_CRISIS_RESOURCES.filter(
    (r) => r.crisisTypes.includes(type) || r.crisisTypes.includes("all-crisis")
  );
}

export function getEmergencyResource(country: string): CrisisResource | undefined {
  const countryMap: Record<string, string[]> = {
    "United States": ["us-911"],
    "Canada": ["ca-911"],
    "United Kingdom": ["uk-999"],
    "Nigeria": ["ng-112"],
    "Ghana": ["gh-112"],
    "Kenya": ["ke-999"],
    "South Africa": ["za-10111"],
    "India": ["in-112"],
    "Australia": ["au-000"],
    "New Zealand": ["nz-111"],
    "Germany": ["de-112"],
    "France": ["fr-112"],
    "Spain": ["es-112"],
    "Brazil": ["br-188"],
    "Mexico": ["mx-911"],
    "Japan": ["jp-110"],
    "South Korea": ["kr-112"],
    "Philippines": ["ph-911"],
  };
  const ids = countryMap[country] || ["global-findahelpline"];
  return VERIFIED_CRISIS_RESOURCES.find((r) => ids.includes(r.id));
}

export const CRISIS_FAQ_ITEMS = [
  {
    q: "What should I do if I feel like hurting myself?",
    a: "Please reach out immediately. Call or text 988 (US), 116 123 (UK), or your local crisis line. If you cannot call, go to your nearest hospital emergency room, call a trusted friend, or reach out via Crisis Text Line (text HOME to 741741 in the US). You matter and help is available right now."
  },
  {
    q: "What should I do if someone I know is suicidal?",
    a: "Stay with them if it is safe to do so. Remove any immediate dangers. Call your local crisis line or emergency services. Do not leave them alone. Do not promise to keep their feelings secret. Let them know they are not alone and that help is available."
  },
  {
    q: "What if I am in danger right now?",
    a: "Call your local emergency number immediately (911 in US/Canada, 999 in UK, 112 in EU/Nigeria, 000 in Australia). If you cannot speak, leave the line open so dispatchers can trace your location. If possible, get to a safe place, alert someone you trust, or go to the nearest hospital, police station, or fire station."
  },
  {
    q: "Is MyTrueSiblings a crisis hotline?",
    a: "No. MyTrueSiblings is not an emergency service, suicide hotline, hospital, police department, or licensed crisis response center. We provide connection, emotional support guidance, and resource navigation to help you find verified crisis support. Always contact professional emergency services for immediate danger."
  },
  {
    q: "Can I speak to someone on MyTrueSiblings?",
    a: "MyTrueSiblings provides peer support, mentorship, and community connection, but we are not a crisis counseling service. If you need immediate crisis support, please use the hotlines and resources listed on this page. Our community will be here when you are ready."
  },
  {
    q: "Is this support free?",
    a: "Yes. All crisis resources listed on this page are free to access. MyTrueSiblings community support is also free. We believe no one should be denied help because of cost."
  },
  {
    q: "Can I use this page anonymously?",
    a: "Yes. This page does not require any login or personal information. Your privacy is protected. If you need additional privacy, please use a private browsing window or clear your browser history afterward."
  },
  {
    q: "What if my country is not listed?",
    a: "Visit Find a Helpline (findahelpline.com) or Befrienders Worldwide (befrienders.org) which together cover 160+ countries. You can also call the global emergency number 112 if available in your region, or go to your nearest hospital or police station."
  },
  {
    q: "Can I report abuse?",
    a: "If you or someone else is in immediate danger, call your local emergency number. For non-emergency reporting: in the US, call the National Domestic Violence Hotline (800-799-7233) or Childhelp (800-422-4453). In the UK, contact the NSPCC (0808 800 5000). Each country has specific reporting services listed in our directory above."
  },
  {
    q: "Can children or teens use this page?",
    a: "Yes. Many resources listed here are specifically for young people: The Trevor Project (US), Kids Help Phone (Canada), Childline (UK), Kids Helpline (Australia), and Nummer gegen Kummer (Germany). If you are a young person in immediate danger, please call emergency services or tell a trusted adult."
  },
  {
    q: "What if I cannot call but can text?",
    a: "Many crisis services offer text support. In the US, text HOME to 741741. In Canada, text 686868. In the UK, text SHOUT to 85258. In New Zealand, text 1737. Check our country-specific resources for more text options."
  },
  {
    q: "What if I am deaf or hard of hearing?",
    a: "Many crisis lines offer TTY, text, chat, and video relay services. In the US, 988 can be reached via TTY: 711 then 988. Crisis Text Line (text HOME to 741741) is fully text-based. The Trevor Project offers chat. Many countries have specific services—check our accessibility section for more options."
  },
];

export const CRISIS_POPUP_MESSAGES = [
  { text: "You are not alone.", emoji: "💛" },
  { text: "Please reach out now.", emoji: "🤝" },
  { text: "Your safety matters.", emoji: "🛡️" },
  { text: "Help is available.", emoji: "🌟" },
  { text: "Someone cares about you.", emoji: "💙" },
];
