export interface Product {
  id: string;
  title: string;
  price: number;
  comparePrice?: number;
  description: string;
  images: string[];
  slogan: string;
  category: string;
  tags: string[];
  colors?: string[];
  sizes?: string[];
  material?: string;
  printifyId?: string;
  isNew?: boolean;
  isBestseller?: boolean;
}

export interface StoreCategory {
  slug: string;
  title: string;
  subtitle: string;
  description: string;
  image: string;
  gradient: string;
  productCount: number;
}

export const STORE_CATEGORIES: StoreCategory[] = [
  {
    slug: "apparel",
    title: "Apparel",
    subtitle: "Wear The Movement",
    description: "Premium tees, hoodies, crewnecks, and more — designed for belonging.",
    image: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800&q=80",
    gradient: "from-brand-teal to-brand-teal/80",
    productCount: 12,
  },
  {
    slug: "wellness",
    title: "Wellness",
    subtitle: "Heal & Thrive",
    description: "Affirmation cards, comfort items, and emotional wellness essentials.",
    image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80",
    gradient: "from-brand-pink-hex to-brand-pink-hex/80",
    productCount: 6,
  },
  {
    slug: "journals",
    title: "Journals & Books",
    subtitle: "Write Your Story",
    description: "Gratitude journals, mental wellness journals, and hope filled notebooks.",
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&q=80",
    gradient: "from-brand-orange-hex to-brand-orange-hex/80",
    productCount: 6,
  },
  {
    slug: "accessories",
    title: "Accessories",
    subtitle: "Carry Connection",
    description: "Phone cases, bracelets, jewelry, backpacks, and daily essentials.",
    image: "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=800&q=80",
    gradient: "from-brand-yellow-hex to-brand-yellow-hex/80",
    productCount: 10,
  },
  {
    slug: "home-living",
    title: "Home & Living",
    subtitle: "Build Belonging At Home",
    description: "Mugs, pillows, blankets, candles, and art that warm your space.",
    image: "https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=800&q=80",
    gradient: "from-brand-red-hex to-brand-red-hex/80",
    productCount: 10,
  },
  {
    slug: "tech",
    title: "Tech",
    subtitle: "Connect Digitally",
    description: "Laptop sleeves, tablet cases, and tech accessories with purpose.",
    image: "https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=800&q=80",
    gradient: "from-brand-teal to-brand-pink-hex",
    productCount: 4,
  },
  {
    slug: "youth",
    title: "Youth Collection",
    subtitle: "Hope Lives Here",
    description: "Designed for young voices to wear their belonging proudly.",
    image: "https://images.unsplash.com/photo-1478115043630-ace4b9e100e4?w=800&q=80",
    gradient: "from-brand-orange-hex to-brand-yellow-hex",
    productCount: 6,
  },
  {
    slug: "inclusive",
    title: "Inclusive Collection",
    subtitle: "Belonging For All",
    description: "Adaptive, accessible, and designed with every sibling in mind.",
    image: "https://images.unsplash.com/photo-1732194438700-c7eb8cc16cb6?w=800&q=80",
    gradient: "from-brand-teal/80 to-brand-teal",
    productCount: 4,
  },
  {
    slug: "hope",
    title: "Hope Collection",
    subtitle: "We Rise Together",
    description: "Products that carry hope, courage, and the promise of tomorrow.",
    image: "https://images.unsplash.com/photo-1543269865-cbf427effbad?w=800&q=80",
    gradient: "from-brand-pink-hex to-brand-orange-hex",
    productCount: 6,
  },
  {
    slug: "community",
    title: "Community Collection",
    subtitle: "Together We Thrive",
    description: "Celebrate the power of community with every piece.",
    image: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=800&q=80",
    gradient: "from-brand-teal to-brand-yellow-hex",
    productCount: 6,
  },
  {
    slug: "gifts",
    title: "Gift Packs",
    subtitle: "Give Belonging",
    description: "Curated gift boxes, comfort kits, and sponsor packs that change lives.",
    image: "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=800&q=80",
    gradient: "from-brand-pink-hex to-brand-red-hex",
    productCount: 6,
  },
];

export const ALL_PRODUCTS: Product[] = [
  // APPAREL
  {
    id: "premium-tshirt",
    title: "Premium tee",
    price: 29.99,
    description: "Soft, breathable Bella Canvas tee with emotional typography. Wear your belonging.",
    images: ["https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=600&q=80"],
    slogan: "You Are Not Alone",
    category: "apparel",
    tags: ["t-shirt", "bestseller", "unisex"],
    colors: ["#FFFFFF", "#009FAF", "#555555", "#FF7A00"],
    sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL"],
    material: "100% Ringspun Cotton",
    isBestseller: true,
  },
  {
    id: "oversized-hoodie",
    title: "Oversized Hoodie",
    price: 54.99,
    description: "Ultra comfortable oversized hoodie. Your cozy armor of belonging.",
    images: ["https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=600&q=80"],
    slogan: "Belonging Matters",
    category: "apparel",
    tags: ["hoodie", "bestseller", "unisex", "cozy"],
    colors: ["#009FAF", "#555555", "#FFFFFF", "#E93D8F"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    material: "80% Cotton / 20% Polyester",
    isBestseller: true,
  },
  {
    id: "crewneck-sweatshirt",
    title: "Crewneck Sweatshirt",
    price: 48.99,
    description: "Classic crewneck with a message of hope. Comfort meets purpose.",
    images: ["https://images.unsplash.com/photo-1578768079052-aa76e52ff62e?w=600&q=80"],
    slogan: "Human Connection Heals",
    category: "apparel",
    tags: ["crewneck", "sweatshirt", "unisex"],
    colors: ["#F2F2F2", "#009FAF", "#555555"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    material: "50% Cotton / 50% Polyester",
  },
  {
    id: "long-sleeve",
    title: "Long Sleeve Shirt",
    price: 34.99,
    description: "Premium long sleeve tee with centered emotional design.",
    images: ["https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=600&q=80"],
    slogan: "Love Listens",
    category: "apparel",
    tags: ["long-sleeve", "premium"],
    colors: ["#FFFFFF", "#009FAF", "#FF7A00"],
    sizes: ["XS", "S", "M", "L", "XL", "2XL"],
    material: "100% Combed Cotton",
  },
  {
    id: "eco-friendly-shirt",
    title: "Eco friendly tee",
    price: 32.99,
    description: "Sustainable style with a message of belonging. Good for you, good for the planet.",
    images: ["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&q=80"],
    slogan: "Built For Belonging",
    category: "apparel",
    tags: ["eco", "sustainable", "t-shirt"],
    colors: ["#FFFFFF", "#555555", "#009FAF"],
    sizes: ["XS", "S", "M", "L", "XL", "2XL"],
    material: "100% Organic Cotton",
  },
  {
    id: "embroidered-hoodie",
    title: "Embroidered Hoodie",
    price: 59.99,
    description: "Elegant embroidered design on premium fleece. Quiet strength. Loud hope.",
    images: ["https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&q=80"],
    slogan: "Connected Hearts",
    category: "apparel",
    tags: ["hoodie", "embroidered", "premium"],
    colors: ["#555555", "#009FAF", "#FFFFFF"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    material: "80% Cotton / 20% Polyester",
  },
  {
    id: "embroidered-hat",
    title: "Embroidered Hat",
    price: 24.99,
    description: "Structured cap with embroidered belonging message. Wear it everywhere.",
    images: ["https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=600&q=80"],
    slogan: "Safe Space",
    category: "apparel",
    tags: ["hat", "cap", "accessory"],
    colors: ["#555555", "#009FAF", "#FFFFFF"],
  },
  {
    id: "joggers",
    title: "Comfort Joggers",
    price: 44.99,
    description: "Soft, fleece lined joggers with subtle branding. Rest in belonging.",
    images: ["https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=600&q=80"],
    slogan: "You Belong Here",
    category: "apparel",
    tags: ["joggers", "comfort", "unisex"],
    colors: ["#555555", "#009FAF", "#F2F2F2"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    material: "80% Cotton / 20% Polyester",
  },
  {
    id: "kids-shirt",
    title: "Kids Believe Tee",
    price: 22.99,
    description: "Soft, playful tee for young siblings. Plant hope early.",
    images: ["https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?w=600&q=80"],
    slogan: "Hope Lives Here",
    category: "youth",
    tags: ["kids", "youth", "t-shirt"],
    colors: ["#009FAF", "#FFC400", "#E93D8F", "#FFFFFF"],
    sizes: ["2T", "3T", "4T", "5", "6", "7", "8", "10", "12"],
    material: "100% Organic Cotton",
  },
  {
    id: "baby-onesie",
    title: "Baby Belonging Onesie",
    price: 18.99,
    description: "Softest organic cotton onesie. Welcome the littlest sibling.",
    images: ["https://images.unsplash.com/photo-1522771930-78848d9293e8?w=600&q=80"],
    slogan: "Born Into Belonging",
    category: "youth",
    tags: ["baby", "onesie", "youth"],
    colors: ["#FFFFFF", "#009FAF", "#FFC400"],
    sizes: ["0-3m", "3-6m", "6-12m", "12-18m", "18-24m"],
    material: "100% Organic Cotton",
  },
  {
    id: "socks",
    title: "Connection Socks",
    price: 12.99,
    description: "Cozy socks with hidden messages of hope. A daily step in belonging.",
    images: ["https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?w=600&q=80"],
    slogan: "Every Step Matters",
    category: "apparel",
    tags: ["socks", "accessory", "cozy"],
    colors: ["#009FAF", "#E93D8F", "#555555", "#FF7A00"],
    sizes: ["S", "M", "L"],
    material: "95% Cotton / 5% Spandex",
  },
  {
    id: "pajama-set",
    title: "Belonging Pajama Set",
    price: 49.99,
    description: "Dream in comfort. Rest in belonging. Premium pajama set for peaceful nights.",
    images: ["https://images.unsplash.com/photo-1616587894289-86480e533129?w=600&q=80"],
    slogan: "Rest In Belonging",
    category: "apparel",
    tags: ["pajama", "sleep", "comfort"],
    colors: ["#009FAF", "#E93D8F", "#555555"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    material: "100% Cotton",
  },

  // ACCESSORIES
  {
    id: "phone-case",
    title: "Love Listens Phone Case",
    price: 32.99,
    description: "Slim, protective phone case. Carry connection in your pocket.",
    images: ["https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=600&q=80"],
    slogan: "Love Listens",
    category: "accessories",
    tags: ["phone-case", "tech", "accessory"],
    colors: ["#009FAF", "#FF7A00", "#555555", "#E93D8F"],
  },
  {
    id: "spiral-notebook",
    title: "Spiral Notebook",
    price: 16.99,
    description: "Premium spiral notebook for your thoughts, dreams, and healing.",
    images: ["https://images.unsplash.com/photo-1531346680769-a1d79b57de5c?w=600&q=80"],
    slogan: "Write Your Story",
    category: "journals",
    tags: ["notebook", "journal", "writing"],
    colors: ["#009FAF", "#E93D8F", "#FF7A00", "#555555"],
  },
  {
    id: "gratitude-journal",
    title: "Gratitude Journal",
    price: 19.99,
    description: "Daily gratitude practice rooted in belonging. 90 days of hope.",
    images: ["https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&q=80"],
    slogan: "Gratitude Heals",
    category: "journals",
    tags: ["journal", "gratitude", "wellness"],
    colors: ["#009FAF", "#FFC400", "#E93D8F"],
  },
  {
    id: "mental-wellness-journal",
    title: "Mental Wellness Journal",
    price: 22.99,
    description: "Guided journal for emotional wellness, reflection, and growth.",
    images: ["https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=600&q=80"],
    slogan: "You Are Not Alone",
    category: "journals",
    tags: ["journal", "mental-health", "wellness"],
    colors: ["#009FAF", "#FF7A00", "#555555"],
  },
  {
    id: "sticker-pack",
    title: "We Rise Together Sticker Pack",
    price: 9.99,
    description: "Set of 10 vinyl stickers with belonging messages. Decorate with hope.",
    images: ["https://images.unsplash.com/photo-1572375992501-4b0892d50c69?w=600&q=80"],
    slogan: "We Rise Together",
    category: "accessories",
    tags: ["stickers", "pack", "accessory"],
    colors: ["#009FAF", "#FFC400", "#F52A3D", "#E93D8F", "#FF7A00"],
  },
  {
    id: "friendship-bracelet",
    title: "Friendship Bracelet",
    price: 14.99,
    description: "Handcrafted bracelet. A daily reminder that you are connected.",
    images: ["https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=600&q=80"],
    slogan: "Connected Hearts",
    category: "accessories",
    tags: ["bracelet", "jewelry", "accessory"],
    colors: ["#009FAF", "#E93D8F", "#FFC400", "#FF7A00"],
  },
  {
    id: "jewelry-set",
    title: "Belonging Necklace",
    price: 28.99,
    description: "Minimalist necklace with belonging charm. Wear your tribe.",
    images: ["https://images.unsplash.com/photo-1515562141589-46a6af5557f0?w=600&q=80"],
    slogan: "Seen. Heard. Valued.",
    category: "accessories",
    tags: ["jewelry", "necklace", "accessory"],
  },
  {
    id: "tote-bag",
    title: "Safe Space Tote Bag",
    price: 24.99,
    description: "Heavy cotton tote. Carry hope everywhere you go.",
    images: ["https://images.unsplash.com/photo-1597484661643-2f5fef640dd1?w=600&q=80"],
    slogan: "Safe Space",
    category: "accessories",
    tags: ["tote", "bag", "eco", "accessory"],
    colors: ["#F2F2F2", "#009FAF", "#555555", "#FF7A00"],
  },
  {
    id: "backpack",
    title: "Community Backpack",
    price: 44.99,
    description: "Spacious, durable backpack. Carry belonging wherever you go.",
    images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80"],
    slogan: "We Rise Together",
    category: "accessories",
    tags: ["backpack", "bag", "accessory"],
    colors: ["#555555", "#009FAF", "#F2F2F2"],
  },
  {
    id: "stationery-set",
    title: "Hope Stationery Set",
    price: 14.99,
    description: "Letter writing set with belonging themed stationery. Send love.",
    images: ["https://images.unsplash.com/photo-1585338107529-13afc5f02586?w=600&q=80"],
    slogan: "Write With Hope",
    category: "accessories",
    tags: ["stationery", "letters", "hope"],
  },

  // HOME & LIVING
  {
    id: "mug",
    title: "Hope Lives Here Mug",
    price: 18.99,
    description: "Ceramic mug. Start every morning with belonging.",
    images: ["https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=600&q=80"],
    slogan: "Hope Lives Here",
    category: "home-living",
    tags: ["mug", "kitchen", "drinkware"],
    colors: ["#FFFFFF", "#009FAF", "#FF7A00", "#E93D8F"],
  },
  {
    id: "pillow",
    title: "Belonging Pillow",
    price: 28.99,
    description: "Soft decorative pillow with embroidered message. Rest in community.",
    images: ["https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=600&q=80"],
    slogan: "You Belong Here",
    category: "home-living",
    tags: ["pillow", "home", "decor"],
    colors: ["#009FAF", "#E93D8F", "#FFC400", "#555555"],
  },
  {
    id: "blanket",
    title: "Comfort Throw Blanket",
    price: 39.99,
    description: "Ultra-soft fleece blanket. Wrapped in warmth and belonging.",
    images: ["https://images.unsplash.com/photo-1617040619263-41c5a9ca7521?w=600&q=80"],
    slogan: "Wrapped In Belonging",
    category: "home-living",
    tags: ["blanket", "comfort", "home"],
    colors: ["#009FAF", "#E93D8F", "#555555", "#F2F2F2"],
  },
  {
    id: "candle",
    title: "Safe Space Candle",
    price: 22.99,
    description: "Soy candle with calming scent. Light hope in your space.",
    images: ["https://images.unsplash.com/photo-1602523961358-f9f03b9d7d17?w=600&q=80"],
    slogan: "Light Hope",
    category: "home-living",
    tags: ["candle", "home", "self-care"],
  },
  {
    id: "poster",
    title: "You Are Not Alone Poster",
    price: 19.99,
    description: "Minimalist typography poster. A daily visual reminder of belonging.",
    images: ["https://images.unsplash.com/photo-1580130379424-b7c76db6b50a?w=600&q=80"],
    slogan: "You Are Not Alone",
    category: "home-living",
    tags: ["poster", "wall-art", "home"],
  },
  {
    id: "wall-art",
    title: "Connected Hearts Print",
    price: 24.99,
    description: "Gallery quality art print. Love that adorns your walls.",
    images: ["https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=600&q=80"],
    slogan: "Connected Hearts",
    category: "home-living",
    tags: ["wall-art", "print", "home"],
  },
  {
    id: "water-bottle",
    title: "Hydrate With Hope Bottle",
    price: 26.99,
    description: "Stainless steel water bottle. Sip belonging all day.",
    images: ["https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&q=80"],
    slogan: "Hope Lives Here",
    category: "home-living",
    tags: ["bottle", "drinkware", "eco"],
    colors: ["#009FAF", "#FFFFFF", "#555555", "#FF7A00"],
  },
  {
    id: "tumbler",
    title: "Belonging Tumbler",
    price: 28.99,
    description: "Insulated tumbler. Keep your hope hot or cold.",
    images: ["https://images.unsplash.com/photo-1570831739435-6601aa3fa4fb?w=600&q=80"],
    slogan: "Built For Belonging",
    category: "home-living",
    tags: ["tumbler", "drinkware", "eco"],
    colors: ["#009FAF", "#E93D8F", "#555555"],
  },
  {
    id: "doormat",
    title: "Welcome Home Doormat",
    price: 32.99,
    description: "Durable coir doormat. Belonging starts at your doorstep.",
    images: ["https://images.unsplash.com/photo-1585409677983-0f6c41ca9c3b?w=600&q=80"],
    slogan: "You Belong Here",
    category: "home-living",
    tags: ["doormat", "home", "outdoor"],
  },
  {
    id: "kitchen-towel",
    title: "Hope Kitchen Towel Set",
    price: 16.99,
    description: "Set of 3 linen kitchen towels. Cook with love, serve with belonging.",
    images: ["https://images.unsplash.com/photo-1583258292688-d0213dc5a3a8?w=600&q=80"],
    slogan: "Love Serves Here",
    category: "home-living",
    tags: ["kitchen", "towel", "home"],
  },

  // TECH
  {
    id: "laptop-sleeve",
    title: "Belonging Laptop Sleeve",
    price: 34.99,
    description: "Padded laptop sleeve. Protect your tech, carry your purpose.",
    images: ["https://images.unsplash.com/photo-1624705002806-5d72df19c3ad?w=600&q=80"],
    slogan: "Built For Belonging",
    category: "tech",
    tags: ["laptop", "tech", "sleeve"],
    colors: ["#555555", "#009FAF", "#F2F2F2"],
    sizes: ["13-inch", "15-inch", "16-inch"],
  },
  {
    id: "tablet-case",
    title: "Connected Tablet Case",
    price: 29.99,
    description: "Slim protective tablet case. Stay connected to community.",
    images: ["https://images.unsplash.com/photo-1564466809058-bf4114d55352?w=600&q=80"],
    slogan: "Stay Connected",
    category: "tech",
    tags: ["tablet", "tech", "case"],
    colors: ["#009FAF", "#E93D8F", "#555555"],
  },
  {
    id: "mouse-pad",
    title: "Hope Mouse Pad",
    price: 12.99,
    description: "Soft mouse pad with daily affirmation. Work with purpose.",
    images: ["https://images.unsplash.com/photo-1629429407759-01cd3d7cfb38?w=600&q=80"],
    slogan: "You Are Enough",
    category: "tech",
    tags: ["mouse-pad", "tech", "desk"],
  },
  {
    id: "tech-pouch",
    title: "Community Tech Pouch",
    price: 19.99,
    description: "Organize your cords and tech with belonging style.",
    images: ["https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=600&q=80"],
    slogan: "Organized With Hope",
    category: "tech",
    tags: ["tech", "pouch", "organizer"],
    colors: ["#009FAF", "#555555", "#E93D8F"],
  },

  // YOUTH
  {
    id: "youth-hoodie",
    title: "Youth Hope Hoodie",
    price: 44.99,
    description: "Cozy hoodie designed for young siblings. Made to inspire.",
    images: ["https://images.unsplash.com/photo-1516826957135-700ded52c6a3?w=600&q=80"],
    slogan: "Hope Lives Here",
    category: "youth",
    tags: ["youth", "hoodie", "hope"],
    colors: ["#009FAF", "#FF7A00", "#555555", "#FFFFFF"],
    sizes: ["XS", "S", "M", "L", "XL"],
    material: "80% Cotton / 20% Polyester",
  },
  {
    id: "youth-backpack",
    title: "Youth Voices Backpack",
    price: 38.99,
    description: "Fun, durable backpack for young siblings. Carry your voice.",
    images: ["https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?w=600&q=80"],
    slogan: "Your Voice Matters",
    category: "youth",
    tags: ["youth", "backpack", "school"],
    colors: ["#009FAF", "#E93D8F", "#FFC400", "#555555"],
  },
  {
    id: "youth-water-bottle",
    title: "Youth Splash Bottle",
    price: 22.99,
    description: "Fun water bottle for young siblings. Hydrate with hope.",
    images: ["https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&q=80"],
    slogan: "You Belong Here",
    category: "youth",
    tags: ["youth", "bottle", "school"],
    colors: ["#009FAF", "#FFC400", "#E93D8F", "#FF7A00"],
  },

  // INCLUSIVE
  {
    id: "adaptive-tshirt",
    title: "Adaptive Belonging Tee",
    price: 34.99,
    description: "Designed for accessibility — magnetic closures, soft seams, and easy on styling.",
    images: ["https://images.unsplash.com/photo-1572490122747-0b6a5ff2e1d0?w=600&q=80"],
    slogan: "Belonging For All",
    category: "inclusive",
    tags: ["adaptive", "inclusive", "accessibility"],
    colors: ["#009FAF", "#FFFFFF", "#555555"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    material: "100% Soft Cotton with Adaptive Features",
  },
  {
    id: "sensory-blanket",
    title: "Sensory Comfort Blanket",
    price: 44.99,
    description: "Weighted sensory blanket. Calming comfort for neurodivergent siblings.",
    images: ["https://images.unsplash.com/photo-1617040619263-41c5a9ca7521?w=600&q=80"],
    slogan: "You Are Safe Here",
    category: "inclusive",
    tags: ["sensory", "blanket", "inclusive", "neurodivergent"],
    colors: ["#009FAF", "#E93D8F", "#555555"],
  },

  // HOPE
  {
    id: "hope-tshirt",
    title: "Hope Lives Here Tee",
    price: 29.99,
    description: "Wear hope on your sleeve. Literally.",
    images: ["https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=600&q=80"],
    slogan: "Hope Lives Here",
    category: "hope",
    tags: ["hope", "t-shirt", "bestseller"],
    colors: ["#FFFFFF", "#FF7A00", "#009FAF", "#555555"],
    sizes: ["XS", "S", "M", "L", "XL", "2XL"],
    isBestseller: true,
  },
  {
    id: "hope-poster-set",
    title: "Hope Poster Set",
    price: 29.99,
    description: "Set of 3 typography posters. Hope for your walls.",
    images: ["https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=600&q=80"],
    slogan: "We Rise Together",
    category: "hope",
    tags: ["poster", "hope", "wall-art", "set"],
  },
  {
    id: "affirmation-cards",
    title: "Affirmation Card Deck",
    price: 16.99,
    description: "52 cards of daily affirmations. Pull hope every morning.",
    images: ["https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&q=80"],
    slogan: "You Are Enough",
    category: "wellness",
    tags: ["affirmation", "cards", "wellness", "self-care"],
  },
  {
    id: "emotional-wellness-kit",
    title: "Emotional Wellness Kit",
    price: 39.99,
    description: "Curated kit with journal, candle, affirmation cards, and comfort items.",
    images: ["https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&q=80"],
    slogan: "Healing Through Connection",
    category: "wellness",
    tags: ["kit", "wellness", "self-care", "gift"],
  },

  // GIFTS
  {
    id: "sponsor-gift-pack",
    title: "Sponsor A Sibling Gift Pack",
    price: 49.99,
    description: "Give the gift of belonging. Includes journal, bracelet, candle, and a card explaining the sibling you supported.",
    images: ["https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&q=80"],
    slogan: "Give Belonging",
    category: "gifts",
    tags: ["gift", "sponsor", "pack", "purpose"],
  },
  {
    id: "comfort-box",
    title: "Comfort Care Box",
    price: 44.99,
    description: "Gentle comfort kit with blanket, tea, candle, journal, and affirmations for someone going through a hard time.",
    images: ["https://images.unsplash.com/photo-1586105251261-72a756497a11?w=600&q=80"],
    slogan: "You Are Not Alone",
    category: "gifts",
    tags: ["gift", "comfort", "care", "wellness"],
  },
  {
    id: "hope-cards-set",
    title: "Hope Cards Collection",
    price: 12.99,
    description: "Set of 8 hope filled cards to send to someone who needs reminding they belong.",
    images: ["https://images.unsplash.com/photo-1585338107529-13afc5f02586?w=600&q=80"],
    slogan: "Send Hope",
    category: "gifts",
    tags: ["cards", "gift", "hope", "stationery"],
  },
  {
    id: "personalized-gift",
    title: "Personalized Support Gift",
    price: 59.99,
    description: "Custom engraved journal with name, message, and a curated comfort package.",
    images: ["https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=600&q=80"],
    slogan: "Made For You",
    category: "gifts",
    tags: ["gift", "personalized", "premium"],
  },

  // COMMUNITY
  {
    id: "community-hoodie",
    title: "Community Hoodie",
    price: 54.99,
    description: "Celebrate community with this premium hoodie. We rise together.",
    images: ["https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&q=80"],
    slogan: "We Rise Together",
    category: "community",
    tags: ["community", "hoodie", "bestseller"],
    colors: ["#009FAF", "#555555", "#FFFFFF", "#FF7A00"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    material: "80% Cotton / 20% Polyester",
    isBestseller: true,
  },
  {
    id: "community-tote",
    title: "Together Tote",
    price: 26.99,
    description: "Room for groceries, books, and belonging. Heavy duty canvas.",
    images: ["https://images.unsplash.com/photo-1597484661643-2f5fef640dd1?w=600&q=80"],
    slogan: "Together We Thrive",
    category: "community",
    tags: ["community", "tote", "eco"],
    colors: ["#F2F2F2", "#009FAF", "#555555"],
  },
  {
    id: "community-mug-set",
    title: "Community Mug Set",
    price: 29.99,
    description: "Set of 4 mugs. Share belonging around your table.",
    images: ["https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=600&q=80"],
    slogan: "Share Belonging",
    category: "community",
    tags: ["community", "mug", "set", "home"],
    colors: ["#009FAF", "#FF7A00", "#FFC400", "#E93D8F"],
  },
  {
    id: "bracelet-set",
    title: "Friendship Bracelet Set",
    price: 19.99,
    description: "Set of 5 woven bracelets. Share one with someone who needs connection.",
    images: ["https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=600&q=80"],
    slogan: "Connected Hearts",
    category: "community",
    tags: ["bracelet", "set", "friendship", "community"],
    colors: ["#009FAF", "#E93D8F", "#FFC400", "#FF7A00", "#555555"],
  },
];

export function getProductsByCategory(slug: string): Product[] {
  return ALL_PRODUCTS.filter((p) => p.category === slug);
}

export function getProductById(id: string): Product | undefined {
  return ALL_PRODUCTS.find((p) => p.id === id);
}

export function getBestsellers(): Product[] {
  return ALL_PRODUCTS.filter((p) => p.isBestseller);
}

export function getNewArrivals(): Product[] {
  return ALL_PRODUCTS.filter((p) => p.isNew);
}

export function getCategory(slug: string): StoreCategory | undefined {
  return STORE_CATEGORIES.find((c) => c.slug === slug);
}
